force-app/main/default/objects/objects/Related_List_Action_Configuration__mdt/fields/Related_List_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Related_List_Configuration__c</fullName>
    <label>Related List Configuration</label>
    <referenceTo>Related_List_Configuration__mdt</referenceTo>
    <relationshipLabel>Related List Action Configurations</relationshipLabel>
    <relationshipName>Related_List_Action_Configurations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Action_Configuration__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <label>Sequence</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/Related_List_Configuration__mdt.object-meta.xml
<CustomObject>
    <description>Configure Parent and Child objects to display in related records using the LWC.</description>
    <label>Related List Configuration</label>
    <pluralLabel>Related List Configurations</pluralLabel>
</CustomObject>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Child_Object__c.field-meta.xml
<CustomField>
    <fullName>Child_Object__c</fullName>
    <description>API Names of the Child Objects.
List of Values have to beRelated objects to the supported Parent Objects.</description>
    <inlineHelpText>Select Child Object related to the Parent Object selected</inlineHelpText>
    <label>Child Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Case</fullName>
                <default>true</default>
                <label>Case</label>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Custom_Actions__c.field-meta.xml
<CustomField>
    <fullName>Custom_Actions__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable to support Row and/or Header level custom actions for the Related List</description>
    <inlineHelpText>Enable record or header level custom actions in Related List</inlineHelpText>
    <label>Enable Custom Actions</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Custom_WHERE_Clause__c.field-meta.xml
<CustomField>
    <fullName>Custom_WHERE_Clause__c</fullName>
    <description>Custom where clause to query the related records.</description>
    <inlineHelpText>Custom where clause to query the related records.</inlineHelpText>
    <label>Custom WHERE Clause</label>
    <type>TextArea</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Delete_Action__c.field-meta.xml
<CustomField>
    <fullName>Delete_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable to support record level Delete action in the Related List</description>
    <inlineHelpText>Enable record level Delete action in the Related List</inlineHelpText>
    <label>Enable Delete Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Edit_Action__c.field-meta.xml
<CustomField>
    <fullName>Edit_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable to record level Edit action in the Related List</description>
    <inlineHelpText>Enable record level Edit action in the Related List</inlineHelpText>
    <label>Enable Edit Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Height__c.field-meta.xml
<CustomField>
    <fullName>Height__c</fullName>
    <defaultValue>300</defaultValue>
    <description>Height of the related list in pixels</description>
    <inlineHelpText>Height of the related list in pixels. Default is 300</inlineHelpText>
    <label>Height</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Icon_BG_Color__c.field-meta.xml
<CustomField>
    <fullName>Icon_BG_Color__c</fullName>
    <inlineHelpText>Background color to be used for the sObject Icon.
e.g for Contacts: #A094ED</inlineHelpText>
    <label>Icon BG Color</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Icon_URL__c.field-meta.xml
<CustomField>
    <fullName>Icon_URL__c</fullName>
    <inlineHelpText>URL for the sObject Icon to display. It can be either standard or from static resource.
e.g for Contacts: /img/icon/t4v35/standard/contact_120.png</inlineHelpText>
    <label>Icon URL</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Infinite_Scrolling__c.field-meta.xml
<CustomField>
    <fullName>Infinite_Scrolling__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable infinite scrolling to load more rows after displaying initial rows specified by &#39;Number of Rows&#39; field</description>
    <inlineHelpText>Enable infinite scrolling to load more rows after displaying initial rows specified by &#39;Number of Rows&#39; field</inlineHelpText>
    <label>Enable Infinite Scrolling</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Layout__c.field-meta.xml
<CustomField>
    <fullName>Layout__c</fullName>
    <description>Display type of related records : Card or List</description>
    <inlineHelpText>Display type of related records : Lightning Card or Standard List</inlineHelpText>
    <label>Layout</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>List</fullName>
                <default>true</default>
                <label>List</label>
            </value>
            <value>
                <fullName>Card</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/New_Action__c.field-meta.xml
<CustomField>
    <fullName>New_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable/Disable to support New Record action in the Related List</description>
    <inlineHelpText>Enable header level New Record action in the Related List</inlineHelpText>
    <label>Enable New Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Number_of_Rows__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Rows__c</fullName>
    <defaultValue>50</defaultValue>
    <description>Number of rows to display by default in the related list, to allow scrolling.</description>
    <inlineHelpText>Number of rows to display by default in the related list, to allow scrolling.</inlineHelpText>
    <label>Number of Rows</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Parent_ID_Field__c.field-meta.xml
<CustomField>
    <fullName>Parent_ID_Field__c</fullName>
    <description>API Name of the ParentId field from the Child Object to use in Where Clause.</description>
    <label>Parent ID Field</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Parent_Object__c.field-meta.xml
<CustomField>
    <fullName>Parent_Object__c</fullName>
    <description>API Names of the Parent Objects.
List of Values have to be one of the Related List lwc supported objects. Refer to the Related List lwc specification for details.</description>
    <inlineHelpText>Select the Parent Object for which the related records to be displayed.</inlineHelpText>
    <label>Parent Object</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Account</fullName>
                <default>true</default>
                <label>Account</label>
            </value>
            <value>
                <fullName>Campaign</fullName>
            </value>
            <value>
                <fullName>Contact</fullName>
            </value>
            <value>
                <fullName>Invoice__c</fullName>
            </value>
            <value>
                <fullName>Lead</fullName>
            </value>
            <value>
                <fullName>Opportunity</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/Upload_Files_Action__c.field-meta.xml
<CustomField>
    <fullName>Upload_Files_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enable Upload Files Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_List_Configuration__mdt/fields/Use_Custom_WHERE_Clause__c.field-meta.xml
<CustomField>
    <fullName>Use_Custom_WHERE_Clause__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable use of custom where clause to query the related records.</description>
    <inlineHelpText>Enable use of custom where clause to query the related records.</inlineHelpText>
    <label>Use Custom WHERE Clause</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Configuration__mdt/fields/View_Action__c.field-meta.xml
<CustomField>
    <fullName>View_Action__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable to support record level View Details action in Related List</description>
    <inlineHelpText>Enable record level View Details action in Related List</inlineHelpText>
    <label>Enable View Action</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Related_List_Field_Configuration__mdt/fields/Field_Label__c.field-meta.xml
<CustomField>
    <fullName>Field_Label__c</fullName>
    <description>Field label to display as column header in the Related List. If this label is not provided, then Original field label corresponding to the Field API name will be used.</description>
    <inlineHelpText>Field label to display as column header in the Related List. If this label is not provided, then Original field label corresponding to the Field API name will be used.</inlineHelpText>
    <label>Field Label</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_List_Field_Configuration__mdt/fields/Field_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_Name__c</fullName>
    <description>API Name of the field to display in Related List.</description>
    <inlineHelpText>API Name of the field to display in Related List.</inlineHelpText>
    <label>Field Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Related_List_Field_Configuration__mdt/fields/Filter__c.field-meta.xml
<CustomField>
    <fullName>Filter__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable filtering by this column. Distinct values in the column will be available as filter values</description>
    <inlineHelpText>Enable filtering by this column. Distinct values in the column will be available as filter values</inlineHelpText>
    <label>Enable Filter</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/objects/Related_List_Field_Configuration__mdt/fields/Filter_Values__c.field-meta.xml
<CustomField>
    <fullName>Filter_Values__c</fullName>
    <description>Comma separated values for filter options, when filter is enabled for the column</description>
    <inlineHelpText>Comma separated values for filter options.</inlineHelpText>
    <label>Filter Values</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Related_List_Field_Configuration__mdt/fields/Related_List_Configuration__c.field-meta.xml
<CustomField>
    <fullName>Related_List_Configuration__c</fullName>
    <description>Associate Parent, Child object combination to consider the field to be displayed.</description>
    <label>Related List Configuration</label>
    <referenceTo>Related_List_Configuration__mdt</referenceTo>
    <relationshipLabel>Related List Field Configurations</relationshipLabel>
    <relationshipName>Related_List_Field_Configurations</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/Related_List_Field_Configuration__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>The position of the column displayed in the Related List.</description>
    <inlineHelpText>The position of the column displayed in the Related List.</inlineHelpText>
    <label>Sequence</label>
    <precision>2</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
    <unique>true</unique>
</CustomField>

force-app/main/default/objects/Related_List_Field_Configuration__mdt/fields/Sortable__c.field-meta.xml
<CustomField>
    <fullName>Sortable__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Enable sorting on the column</description>
    <inlineHelpText>Enable sorting on the column</inlineHelpText>
    <label>Sortable</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/RelatedRecordService.cls
public with sharing class RelatedRecordService {
    private static RLConfig config;
    
    @AuraEnabled(cacheable=true)
    public static RLConfig getRelatedListConfigDetails( String rlcName ) {
        try {
            
            List<Related_List_Configuration__mdt> listOfRLConfigurations = getRelatedListConfigMetadata(rlcName);
            
            Related_List_Configuration__mdt rlConfig = listOfRLConfigurations[0];
            
            //
            // Create RLConfig instance to send back.
            //
            config = new RLConfig();
            config.title = rlConfig.MasterLabel;
            config.iconurl = rlConfig.Icon_URL__c;
            config.iconBGColor = rlConfig.Icon_BG_Color__c;
            config.parentObject = rlConfig.Parent_Object__c;
            config.childObject = rlConfig.Child_Object__c;
            config.parentIdField = rlConfig.Parent_ID_Field__c;
            config.noOfRows = Integer.valueOf(rlConfig.Number_of_Rows__c);
            config.enableInfiniteScrolling = rlConfig.Infinite_Scrolling__c;
            config.enableCustomActions = rlConfig.Custom_Actions__c;
            config.enableDeleteAction = rlConfig.Delete_Action__c;
            config.enableEditAction = rlConfig.Edit_Action__c;
            config.enableNewAction = rlConfig.New_Action__c;
            config.enableViewAction = rlConfig.View_Action__c;
            config.useCustomWhereClause = rlConfig.Use_Custom_WHERE_Clause__c;
            config.customWhereClause = rlConfig.Custom_WHERE_Clause__c;
            config.layout = rlConfig.Layout__c;
            config.height = Integer.valueOf(rlConfig.Height__c);

            //
            // Get child relationship name
            //
            List<Schema.DescribeSObjectResult> describeSobjects = Schema.describeSObjects(new List<String>{rlConfig.Parent_Object__c});
            for(Schema.Childrelationship eachRelationship : describeSobjects[0].getChildRelationships()){
                if(eachRelationship.getChildSObject().getDescribe().getLocalName() == rlConfig.Child_Object__c){
                    config.relationshipName = String.valueOf(eachRelationship.getRelationshipName());
                }
            }

            //
            //  Create Columns 
            //
            describeSobjects = Schema.describeSObjects(new List<String>{rlConfig.Child_Object__c});
            
            if (rlConfig.getSObjects('Related_List_Field_Configurations__r') != null && rlConfig.getSObjects('Related_List_Field_Configurations__r').size() != 0){
                RelatedRecordService.RLField field;
                for (Sobject eachCh : (List<SObject>)rlConfig.getSObjects('Related_List_Field_Configurations__r')) {
                    if(eachCh.get('Field_Name__c') != null){
                        field = new RelatedRecordService.RLField();
                        
                        field.fieldName = String.valueOf(eachCh.get('Field_Name__c'));
                        field.label = String.valueOf(eachCh.get('Field_Label__c'));
                        if(String.isEmpty(field.label)){
                            field.label = describeSobjects[0].fields.getMap().get(String.valueOf(eachCh.get('Field_Name__c'))).getDescribe().getName();
                        }
                        
                        field.sequence = Integer.valueOf(eachCh.get('Sequence__c'));
                        field.type = describeSobjects[0].fields.getMap().get(String.valueOf(eachCh.get('Field_Name__c'))).getDescribe().getType().name();
                        field.sortable = Boolean.valueOf(eachCh.get('Sortable__c'));
                        field.enableFilter = Boolean.valueOf(eachCh.get('Filter__c'));
                        field.filterValues = String.valueOf(eachCh.get('Filter_Values__c'));
                        //
                        // Get Column Header level actions, if any. These need to be set at individual column/field
                        //
                        setColumnHeaderActions(field, rlConfig, describeSobjects[0]);
                        config.fields.add(field);
                    }
                }

                //
                // Get row level actions. these need to be added to the columns/fields array
                //
                setRowAndListActions(rlConfig, describeSobjects[0]);
            }                
            
            return config;
            
        }
        catch(Exception e) {
            System.debug(e.getStackTraceString());
            throw new AuraHandledException(e.getMessage());
        }
    }

    private static void setRowAndListActions(Related_List_Configuration__mdt rlConfig, Schema.DescribeSObjectResult describeSobject){
        
        List<RelatedRecordService.RLAction> actions = new List<RelatedRecordService.RLAction>();
        if(rlConfig.Upload_Files_Action__c){
            RelatedRecordService.RLAction action = new RelatedRecordService.RLAction();
            action.label = 'Upload Files';action.name = 'Files';action.actionURL = '';action.type = 'ListAction';action.isFileUpload=true;
            actions.add(action);
        }
        if(rlConfig.New_Action__c && describeSobject.isCreateable()){
            RelatedRecordService.RLAction action = new RelatedRecordService.RLAction();
            action.label = 'New';action.name = 'New';action.actionURL = '';action.type = 'ListAction';
            actions.add(action);
        }
        if(rlConfig.Edit_Action__c && describeSobject.isUpdateable()){
            RelatedRecordService.RLAction action = new RelatedRecordService.RLAction();
            action.label = 'Edit';action.name = 'Edit';action.actionURL = '';action.type = 'RowAction';
            actions.add(action);
        }
        if(rlConfig.View_Action__c && describeSobject.isAccessible()){
            RelatedRecordService.RLAction action = new RelatedRecordService.RLAction();
            action.label = 'View';action.name = 'View';action.actionURL = '';action.type = 'RowAction';
            actions.add(action);
        }
        if(rlConfig.Delete_Action__c && describeSobject.isDeletable()){
            RelatedRecordService.RLAction action = new RelatedRecordService.RLAction();
            action.label = 'Delete';action.name = 'Delete';action.actionURL = '';action.type = 'RowAction';
            actions.add(action);
        }
        //
        // If Custom Actions are enabled, then get Custom Row and List Actions configuration details, and add to columns/fields array
        // 
        if(rlConfig.Custom_Actions__c){
            if (rlConfig.getSObjects('Related_List_Action_Configurations__r') != null && rlConfig.getSObjects('Related_List_Action_Configurations__r').size() != 0){
                RelatedRecordService.RLAction action;
                for (Sobject eachCh : (List<SObject>)rlConfig.getSObjects('Related_List_Action_Configurations__r')) {
                    action = new RelatedRecordService.RLAction();
                    action.label = String.valueOf(eachCh.get('MasterLabel'));
                    action.name = String.valueOf(eachCh.get('DeveloperName'));
                    action.type = String.valueOf(eachCh.get('Type__c'));
                    action.actionURL = String.valueOf(eachCh.get('Action_URL__c'));
                    action.targetType = String.valueOf(eachCh.get('Target_Type__c'));
                    action.params = String.valueOf(eachCh.get('Parameters__c'));
                    action.sequence = Integer.valueOf(eachCh.get('Sequence__c'));
                    actions.add(action);
                }
            }   
        }

        if(actions.size() > 0){
            config.actions.addAll(actions);
        }
    }

    private static void setColumnHeaderActions(RelatedRecordService.RLField field,  Related_List_Configuration__mdt rlConfig, Schema.DescribeSObjectResult describeSobject){
        //
        // If Custom Actions are enabled, then get Custom Column Header Action configuration details, and add to individual field
        // 
        if(rlConfig.Custom_Actions__c){
            
        }
    }

    private static List<Related_List_Configuration__mdt> getRelatedListConfigMetadata(String rlcName){
        //
        // Query Related List configuration details, including field and custom action configurations.
        // 
        String fieldListConfigQuery = 'SELECT Field_Label__c, Field_Name__c, Sequence__c, Sortable__c, Filter__c, Filter_Values__c '
                                    + 'FROM Related_List_Field_Configurations__r '
                                    + 'WHERE Active__c = true ORDER BY Sequence__c ASC';
        
        String actionConfigQuery = 'SELECT MasterLabel, DeveloperName, Type__c, Action_URL__c, Target_Type__c, Parameters__c, Sequence__c '
                                    + 'FROM Related_List_Action_Configurations__r '
                                    + 'WHERE Active__c = true ORDER BY Sequence__c ASC';

        String queryRLConfiguration = 'SELECT Id, MasterLabel, DeveloperName, '
                                    + 'Active__c, '
                                    + 'Parent_Object__c, '
                                    + 'Child_Object__c, '
                                    + 'Icon_URL__c, '
                                    + 'Icon_BG_Color__c, '
                                    + 'Parent_ID_Field__c, '
                                    + 'Number_of_Rows__c, '
                                    + 'New_Action__c, '
                                    + 'Edit_Action__c, '
                                    + 'View_Action__c, '
                                    + 'Delete_Action__c, '
                                    + 'Upload_Files_Action__c, '
                                    + 'Custom_Actions__c, '
                                    + 'Infinite_Scrolling__c, '
                                    + 'Use_Custom_WHERE_Clause__c, '
                                    + 'Custom_WHERE_Clause__c, '
                                    + 'Layout__c, '
                                    + 'Height__c, '
                                    + '(' + fieldListConfigQuery + '), '
                                    + '(' + actionConfigQuery + ') '
                                + 'FROM Related_List_Configuration__mdt '
                                + 'WHERE Active__c = true AND '
                                + 'DeveloperName =:rlcName LIMIT 1';
                                
        //System.debug('queryRLConfiguration'+queryRLConfiguration);
        List<Related_List_Configuration__mdt> listOfRLConfigurations = Database.query( queryRLConfiguration );

        return listOfRLConfigurations;
    }
    
    @AuraEnabled(cacheable=true)
    public static List<SObject> getRelatedData( String rlcName, String parentId ) {
        List<SObject> records = new List<SObject>();
        try{
            config = getRelatedListConfigDetails(rlcName);
            String fieldList = '';
            for(RelatedRecordService.RLField fld : config.fields){
                fieldList += fld.fieldName + ',';
            }
            fieldList = fieldList.removeEnd(',');

            String sQuery = 'SELECT Id,'
            + fieldList
            + ' FROM ' + config.childObject
            + ' WHERE ' + config.parentIdField + '=\'' + ID.valueOf(parentId) + '\''; 
            if(config.useCustomWhereClause && !String.isEmpty(config.customWhereClause)){
                sQuery += ' AND (' + config.customWhereClause + ')';
            }
            
            records = Database.query( sQuery );
        }
        catch(Exception e) {
            System.debug('error::' + e.getMessage());
            throw new AuraHandledException(e.getMessage());
        }
        return records;
    }

    public class RLConfig {
        @AuraEnabled public String title;
        @AuraEnabled public String iconurl;
        @AuraEnabled public String iconBGColor;
        @AuraEnabled public String parentObject;
        @AuraEnabled public String childObject;
        @AuraEnabled public String relationshipName;
        @AuraEnabled public String parentIdField;
        @AuraEnabled public Integer noOfRows;
        @AuraEnabled public List<RLField> fields = new List<RLField>();
        @AuraEnabled public List<RLAction> actions = new List<RLAction>();
        @AuraEnabled public Boolean enableCustomActions;
        @AuraEnabled public Boolean enableNewAction;
        @AuraEnabled public Boolean enableEditAction;
        @AuraEnabled public Boolean enableViewAction;
        @AuraEnabled public Boolean enableDeleteAction;
        @AuraEnabled public Boolean enableInfiniteScrolling;
        @AuraEnabled public Boolean useCustomWhereClause;
        @AuraEnabled public String customWhereClause;     
        @AuraEnabled public String layout;          
        @AuraEnabled public Integer height;                      
    }
    private class RLField{
        @AuraEnabled public String label;
        @AuraEnabled public String fieldName;
        @AuraEnabled public String type;
        @AuraEnabled public Boolean enableFilter;
        @AuraEnabled public String filterValues;
        @AuraEnabled public Integer sequence;
        @AuraEnabled public Boolean sortable;
        
        //@AuraEnabled public String editable;
    }
    private class RLAction{
        @AuraEnabled public String label;
        @AuraEnabled public String name;
        @AuraEnabled public String type;
        @AuraEnabled public String actionURL;
        @AuraEnabled public String targetType;
        @AuraEnabled public String params;
        @AuraEnabled public Integer sequence;
        @AuraEnabled public Boolean isFileUpload = false;
    }

}